# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automated System Test

on:
  push:
    branches: [ test.yaml-rob ] 

jobs:
  build:

    runs-on: [pelican]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - run: python -V
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          pip install --upgrade pip setuptools wheel &>/dev/null
          pip show setuptools &>/dev/null
          python -m pip install git+https://github.com/NextCenturyCorporation/MCS@0.3.8
          pip install -r requirements.txt &>/dev/null
          bash setup_torch.sh &>/dev/null
          bash setup_unity.sh
          bash setup_vision.sh &>/dev/null
          export PYTHONPATH=$PWD
      - name: Run evaluation code on scenes
        run: |
          python get_gravity_scenes.py
          python eval.py --scenes gravity_scenes
