# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automated System Test

on:
  push:
    branches: [ test.yaml-rob ] 

jobs:
  build:

    runs-on: [submit]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: launch gpu equipped runner
        run: |
          echo "cd /scratch/mcs/actions-runner; nohup ./run.sh & sleep 6" > /tmp/ga_run && srun -A eecs -gpu --nodelist=cn-gpu2 --gres=gpu:1 --pty /tmp/ga_run
