# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automated System Test

on:
  push:
    branches: [ test.yaml-rob ] 

jobs:
  start-gpu-runner:
    runs-on: [pelican]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: make slurm script
        run: |
          printf "#!/bin/bash
          #SBATCH -J mcs_ga_build  # name of job
          #SBATCH -A eecs          # sponsored account
          #SBATCH -p gpu           # partition or queue
          #SBATCH -o mcs.out       # output file
          #SBATCH -e mcs.err       # error file
          #SBATCH --nodelist=cn-gpu2
          nohup /scratch/MCS/actions-runner/run.sh &
          export MCS_PID=\$!
          # sleep time must match cleanup time below!
          sleep 1e4 # ~3 hrs" > /tmp/mcs.sh
      - name: launch gpu equipped runner
        run: |
          # give slurm script to the submit server
          scp /tmp/mcs.sh $USER@submit-b.hpc.engr.oregonstate.edu:/tmp/mcs.sh
          ssh -tt $USER@submit-b.hpc.engr.oregonstate.edu "source /etc/profile; module load slurm; sbatch /tmp/mcs.sh"
  gpu-runner-build:
    needs: start-gpu-runner
    runs-on: [cn-gpu2]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: load modules
        run: |
          module load gcc/6.5
          module load anaconda
      - name: install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          export DISPLAY=:0
          conda create -n mcs_opics python=3.6.8
          conda activate mcs_opics
          pip install --upgrade pip setuptools wheel
          python -m pip install git+https://github.com/NextCenturyCorporation/MCS@0.3.8
          pip install -r requirements.txt
          pip show ai2thor
          bash setup_torch.sh
          bash setup_unity.sh
          bash setup_vision.sh
          export PYTHONPATH=$PWD
      - name: test latest code
        run: |
          python eval.py
      - name: cleanup
        if: always()
        run: |
          # if you change the sleep time above, this needs changed too
          pgrep sleep | xargs ps | grep 1e4 | cut -d ' ' -f 1 | xargs kill
