# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automated System Test

on:
  push:
    branches: [ test.yaml-rob ] 

jobs:
  build:
    runs-on: [pelican]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: make slurm script
        run: |
          printf "
            #!/bin/bash
            #SBATCH -J mcs_ga_build  # name of job
            #SBATCH -A eecs          # name of my sponsored account, e.g. class or research group, NOT ONID!
            #SBATCH -p gpu           # name of partition or queue
            #SBATCH -o mcs.out       # name of output file for this submission script
            #SBATCH -e mcs.err       # name of error file for this submission script
            #SBATCH --nodelist=cn-gpu2
            module load gcc/6.5
            nohup /scratch/MCS/actions-runner/run.sh &
            export MCS_PID=$$!
            sleep 1e4 # 3 hrs
          " > /tmp/mcs.sh
      - name: launch gpu equipped runner
        run: |
          # give slurm script to the submit server
          scp /tmp/mcs.sh $USER@submit-b.hpc.engr.oregonstate.edu:/tmp/mcs.sh
          ssh $USER@submit-b.hpc.engr.oregonstate.edu "module load slurm; sbatch /tmp/mcs.sh"
  notify:
    needs: build
    runs-on: [cn-gpu2]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: load modules
        run: |
          module load gcc/6.5
          module load anaconda
      - name: install python dependencies
        run: |
          conda create env --name mcs_opics --v 3.6.8
          pip -m install requirements.txt
      - name: cleanup
        if: always()
        run: |
          echo $MCS_PID
          kill $MCS_PID
